#!/usr/bin/env python3

import os
import sys

from midi_ml.tools.util import download_from_gcs

download_from_gcs(bucket_name=sys.argv[1],
                  prefix=sys.argv[2],
                  local_fs_loc=sys.argv[3])
