#!/usr/bin/env python3

import logging
import argparse
from midi_ml.pipelines import midi_reads, train_and_evaluate

# TODO: set the debug level as global option
logger = logging.getLogger(__name__)
logger.setLevel("DEBUG")


def main(args):
    logger.info("starting pipeline")
    if args.pipeline == "midi-reads":
        midi_reads.main()
    elif args.pipeline == "model-train":
        train_and_evaluate.main()
    else:
        raise ValueError("Please select a valid pipeline")


if __name__ == '__main__':
    logger.info("starting pipeline main")
    parser = argparse.ArgumentParser(description="Runs the midi-ml pipeline")
    parser.add_argument("pipeline")
    main(parser.parse_args())
